"""añade modelo PlantillaActa

Revision ID: 0203bf29390f
Revises: 5f78a22b66eb
Create Date: 2025-07-18 08:36:04.129423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0203bf29390f'
down_revision = '5f78a22b66eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plantilla_acta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('html', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plantilla_acta')
    # ### end Alembic commands ###
