"""Añadir campo firma a Formador

Revision ID: 052c80dd43e6
Revises: 8a84bb3f4a31
Create Date: 2025-07-30 01:19:25.619926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '052c80dd43e6'
down_revision = '8a84bb3f4a31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('formador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firma', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('formador', schema=None) as batch_op:
        batch_op.drop_column('firma')

    # ### end Alembic commands ###
