"""forzar cambio en PlantillaDiploma

Revision ID: 102784a696b7
Revises: ec495e6cf783
Create Date: 2025-07-22 18:23:21.195498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '102784a696b7'
down_revision = 'ec495e6cf783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantilla_diploma', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archivo_pdf', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('coordenadas_nombre', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('coordenadas_dni', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('coordenadas_fecha', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('coordenadas_curso', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('coordenadas_empresa', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('coordenadas_horas', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('coordenadas_instructor', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('dummy', sa.String(length=1), nullable=True))
        batch_op.alter_column('html',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantilla_diploma', schema=None) as batch_op:
        batch_op.alter_column('html',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('dummy')
        batch_op.drop_column('coordenadas_instructor')
        batch_op.drop_column('coordenadas_horas')
        batch_op.drop_column('coordenadas_empresa')
        batch_op.drop_column('coordenadas_curso')
        batch_op.drop_column('coordenadas_fecha')
        batch_op.drop_column('coordenadas_dni')
        batch_op.drop_column('coordenadas_nombre')
        batch_op.drop_column('archivo_pdf')

    # ### end Alembic commands ###
