"""create permissions table

Revision ID: 1a6643c61a84
Revises: a9a36dfac66e
Create Date: 2025-08-20 10:21:53.798208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a6643c61a84'
down_revision = 'a9a36dfac66e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_permissions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'permission_id')
    )
    with op.batch_alter_table('examen_alumno', schema=None) as batch_op:
        batch_op.add_column(sa.Column('examen_modelo_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('nota', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fecha', sa.Date(), nullable=True))
        batch_op.create_foreign_key('fk_examen_alumno_examen_modelo', 'examen_modelo', ['examen_modelo_id'], ['id'])
        batch_op.drop_column('nota_automatica')
        batch_op.drop_column('respuestas_json')

    with op.batch_alter_table('plantilla_acta', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=120),
               nullable=False)
        batch_op.drop_column('acta_docx')

    with op.batch_alter_table('pregunta', schema=None) as batch_op:
        batch_op.alter_column('texto',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('examen_modelo_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('respuesta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correcta', sa.Boolean(), nullable=True))
        batch_op.alter_column('texto',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.drop_column('es_correcta')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('respuesta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_correcta', sa.BOOLEAN(), nullable=True))
        batch_op.alter_column('texto',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
        batch_op.drop_column('correcta')

    with op.batch_alter_table('pregunta', schema=None) as batch_op:
        batch_op.alter_column('examen_modelo_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('texto',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)

    with op.batch_alter_table('plantilla_acta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acta_docx', sa.VARCHAR(length=255), nullable=True))
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=200),
               nullable=True)

    with op.batch_alter_table('examen_alumno', schema=None) as batch_op:
        batch_op.add_column(sa.Column('respuestas_json', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('nota_automatica', sa.FLOAT(), nullable=True))
        batch_op.drop_constraint('fk_examen_alumno_examen_modelo', type_='foreignkey')
        batch_op.drop_column('fecha')
        batch_op.drop_column('nota')
        batch_op.drop_column('examen_modelo_id')

    op.drop_table('user_permissions')
    op.drop_table('permission')
    # ### end Alembic commands ###
