"""forzar cambio en PlantillaDiploma

Revision ID: 2db184150ce1
Revises: 102784a696b7
Create Date: 2025-07-22 18:24:53.692616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2db184150ce1'
down_revision = '102784a696b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantilla_diploma', schema=None) as batch_op:
        batch_op.drop_column('dummy')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantilla_diploma', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dummy', sa.VARCHAR(length=1), nullable=True))

    # ### end Alembic commands ###
