"""Add es_correcta to Respuesta

Revision ID: 449b8ee7bc00
Revises: 1a6643c61a84
Create Date: 2025-08-25 12:47:08.740954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '449b8ee7bc00'
down_revision = '1a6643c61a84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('respuesta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_correcta', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('respuesta', schema=None) as batch_op:
        batch_op.drop_column('es_correcta')

    # ### end Alembic commands ###
