"""Añade campo pdf_objetivos a TipoCurso

Revision ID: 5849cb749ac6
Revises: 3c05f0dba7bb
Create Date: 2025-08-01 23:19:17.445509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5849cb749ac6'
down_revision = '3c05f0dba7bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo_curso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_objetivos', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo_curso', schema=None) as batch_op:
        batch_op.drop_column('pdf_objetivos')

    # ### end Alembic commands ###
