"""Migración inicial tras limpieza

Revision ID: 66263093ce11
Revises: 
Create Date: 2025-07-11 20:33:52.835489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66263093ce11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comercial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('telefono', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('examen_modelo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('formador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('telefono', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=False),
    sa.Column('cif', sa.String(length=32), nullable=False),
    sa.Column('direccion', sa.String(length=256), nullable=True),
    sa.Column('poblacion', sa.String(length=64), nullable=True),
    sa.Column('provincia', sa.String(length=64), nullable=True),
    sa.Column('contacto', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('telefono', sa.String(length=32), nullable=True),
    sa.Column('comercial_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comercial_id'], ['comercial.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cif'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('pregunta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=512), nullable=False),
    sa.Column('examen_modelo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['examen_modelo_id'], ['examen_modelo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_curso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=False),
    sa.Column('duracion_horas', sa.Integer(), nullable=True),
    sa.Column('temario', sa.Text(), nullable=True),
    sa.Column('objetivos', sa.Text(), nullable=True),
    sa.Column('pdf_temario', sa.String(length=255), nullable=True),
    sa.Column('validez_meses', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('requiere_renovacion', sa.Boolean(), nullable=False),
    sa.Column('examen_modelo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['examen_modelo_id'], ['examen_modelo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alumno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('dni', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('interesado_mas_cursos', sa.Boolean(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('email')
    )
    op.create_table('formacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referencia', sa.String(length=32), nullable=True),
    sa.Column('tipo_curso_id', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('dos_ediciones', sa.Boolean(), nullable=True),
    sa.Column('fecha1', sa.Date(), nullable=True),
    sa.Column('hora_inicio1', sa.Time(), nullable=True),
    sa.Column('hora_fin1', sa.Time(), nullable=True),
    sa.Column('fecha2', sa.Date(), nullable=True),
    sa.Column('hora_inicio2', sa.Time(), nullable=True),
    sa.Column('hora_fin2', sa.Time(), nullable=True),
    sa.Column('direccion_aula', sa.String(length=256), nullable=True),
    sa.Column('fundae', sa.Boolean(), nullable=True),
    sa.Column('formador_id', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('cerrada', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['formador_id'], ['formador.id'], ),
    sa.ForeignKeyConstraint(['tipo_curso_id'], ['tipo_curso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('formador_tipo_curso',
    sa.Column('formador_id', sa.Integer(), nullable=False),
    sa.Column('tipo_curso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['formador_id'], ['formador.id'], ),
    sa.ForeignKeyConstraint(['tipo_curso_id'], ['tipo_curso.id'], ),
    sa.PrimaryKeyConstraint('formador_id', 'tipo_curso_id')
    )
    op.create_table('respuesta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=256), nullable=False),
    sa.Column('es_correcta', sa.Boolean(), nullable=True),
    sa.Column('pregunta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pregunta_id'], ['pregunta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alumno_formacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=True),
    sa.Column('formacion_id', sa.Integer(), nullable=True),
    sa.Column('aprobado', sa.Boolean(), nullable=True),
    sa.Column('nota', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumno.id'], ),
    sa.ForeignKeyConstraint(['formacion_id'], ['formacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('examen_alumno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumno_formacion_id', sa.Integer(), nullable=True),
    sa.Column('respuestas_json', sa.Text(), nullable=True),
    sa.Column('nota_automatica', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_formacion_id'], ['alumno_formacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('examen_alumno')
    op.drop_table('alumno_formacion')
    op.drop_table('respuesta')
    op.drop_table('formador_tipo_curso')
    op.drop_table('formacion')
    op.drop_table('alumno')
    op.drop_table('tipo_curso')
    op.drop_table('pregunta')
    op.drop_table('empresa')
    op.drop_table('formador')
    op.drop_table('examen_modelo')
    op.drop_table('comercial')
    # ### end Alembic commands ###
