"""Eliminar coordenadas y renombrar archivo_pdf a ruta_pdf

Revision ID: 8a84bb3f4a31
Revises: 2db184150ce1
Create Date: 2025-07-26 13:51:21.591885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a84bb3f4a31'
down_revision = '2db184150ce1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantilla_diploma', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ruta_pdf', sa.String(length=255), nullable=True))
        batch_op.drop_column('coordenadas_instructor')
        batch_op.drop_column('diploma_docx')
        batch_op.drop_column('coordenadas_fecha')
        batch_op.drop_column('coordenadas_dni')
        batch_op.drop_column('coordenadas_nombre')
        batch_op.drop_column('coordenadas_curso')
        batch_op.drop_column('coordenadas_horas')
        batch_op.drop_column('coordenadas_empresa')
        batch_op.drop_column('archivo_pdf')
        batch_op.drop_column('html')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantilla_diploma', schema=None) as batch_op:
        batch_op.add_column(sa.Column('html', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('archivo_pdf', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('coordenadas_empresa', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('coordenadas_horas', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('coordenadas_curso', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('coordenadas_nombre', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('coordenadas_dni', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('coordenadas_fecha', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('diploma_docx', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('coordenadas_instructor', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('ruta_pdf')

    # ### end Alembic commands ###
