"""añade plantilla_acta_id a TipoCurso

Revision ID: 8b15c1a6a13c
Revises: 0203bf29390f
Create Date: 2025-07-18 08:38:31.172425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b15c1a6a13c'
down_revision = '0203bf29390f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo_curso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plantilla_acta_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_tipocurso_plantilla_acta', 'plantilla_acta', ['plantilla_acta_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo_curso', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('plantilla_acta_id')

    # ### end Alembic commands ###
