"""Añade campo poblacion a Formacion

Revision ID: a9a36dfac66e
Revises: b48545cacd34
Create Date: 2025-08-11 20:29:39.793678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9a36dfac66e'
down_revision = 'b48545cacd34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_column('email')

    with op.batch_alter_table('formacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poblacion', sa.String(length=128), nullable=True))

    with op.batch_alter_table('plantilla_acta', schema=None) as batch_op:
        batch_op.drop_column('html')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantilla_acta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('html', sa.TEXT(), nullable=True))

    with op.batch_alter_table('formacion', schema=None) as batch_op:
        batch_op.drop_column('poblacion')

    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=128), nullable=True))

    # ### end Alembic commands ###
