"""añadir tabla PlantillaDiploma

Revision ID: acc80a25ac51
Revises: 66263093ce11
Create Date: 2025-07-18 00:10:54.056042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acc80a25ac51'
down_revision = '66263093ce11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plantilla_diploma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('html', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plantilla_diploma')
    # ### end Alembic commands ###
