"""Add examen_alumno_id to Respuesta and relación en ExamenAlumno

Revision ID: bd04513a6f2f
Revises: cfef27d81a79
Create Date: 2025-08-25 18:47:10.784724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd04513a6f2f'
down_revision = 'cfef27d81a79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('respuesta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('examen_alumno_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_respuesta_examen_alumno', 'examen_alumno', ['examen_alumno_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('respuesta', schema=None) as batch_op:
        batch_op.drop_constraint('fk_respuesta_examen_alumno', type_='foreignkey')
        batch_op.drop_column('examen_alumno_id')

    # ### end Alembic commands ###
