"""Add nota_automatica to ExamenAlumno

Revision ID: cfef27d81a79
Revises: 449b8ee7bc00
Create Date: 2025-08-25 18:35:42.378208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfef27d81a79'
down_revision = '449b8ee7bc00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examen_alumno', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nota_automatica', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examen_alumno', schema=None) as batch_op:
        batch_op.drop_column('nota_automatica')

    # ### end Alembic commands ###
