"""añade campo docx a plantilla diploma y/o acta

Revision ID: d6b1f04273b5
Revises: 8b15c1a6a13c
Create Date: 2025-07-18 09:59:21.966245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6b1f04273b5'
down_revision = '8b15c1a6a13c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantilla_acta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acta_docx', sa.String(length=255), nullable=True))

    with op.batch_alter_table('plantilla_diploma', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diploma_docx', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantilla_diploma', schema=None) as batch_op:
        batch_op.drop_column('diploma_docx')

    with op.batch_alter_table('plantilla_acta', schema=None) as batch_op:
        batch_op.drop_column('acta_docx')

    # ### end Alembic commands ###
