"""añade campo acta_docx a plantilla_acta

Revision ID: ec495e6cf783
Revises: d6b1f04273b5
Create Date: 2025-07-18 15:05:12.362217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec495e6cf783'
down_revision = 'd6b1f04273b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantilla_acta', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=200),
               nullable=True)
        batch_op.alter_column('html',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantilla_acta', schema=None) as batch_op:
        batch_op.alter_column('html',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###
